project:
  type: book
  title: "现代计算机视觉"

# Thesis-specific metadata
thesis-title: "现代计算机视觉"
author: 
  - name: "AI Assistant & You"
supervisor: 
  - name: "Supervisor Name"
degree: "Doctor of Philosophy"
degree-year: "2025"
declaration-text: "This is my declaration."
acknowledgements-text: "I want to thank..."

book:
  title: "现代计算机视觉"
  author: "AI Assistant & You"
  date: "today"
  chapters:
    - index.qmd
    - part: "第十一章：三维视觉与点云处理"
      chapters:
        - chapter11/11.0_概述.qmd
        - chapter11/11.1_相机标定与几何.qmd
        - chapter11/11.2_立体匹配与深度估计.qmd
        - chapter11/11.3_三维重建.qmd
        - chapter11/11.4_点云基础与处理.qmd
        - chapter11/11.5_PointNet系列网络.qmd
        - chapter11/11.6_3D目标检测.qmd
        - chapter11/11.7_应用案例分析.qmd
    - references.qmd

# lang: zh-CN  # 暂时注释避免翻译警告
bibliography: references.bib

format:
  html:
    # 主题优化 - 适合技术书籍阅读
    theme:
      light: cosmo
      dark: slate
    
    # 代码配置 - 适合计算机视觉代码
    highlight-style: github
    code-copy: true
    code-fold: show
    code-line-numbers: true
    code-tools: true
    
    # 字体优化 - 中文技术书籍
    mainfont: "PingFang SC"
    monofont: "SF Mono"
    
    # 布局优化 - 适合长章节
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "章节目录"
    number-sections: true
    number-depth: 3
    
    # 图表配置 - 计算机视觉需要大量图表
    fig-cap-location: bottom
    fig-align: center
    fig-responsive: true
    tbl-cap-location: top
    
    # 交互功能
    smooth-scroll: true
    anchor-sections: true
    back-to-top-navigation: true
    
    # 搜索功能
    search: true
      
    # 数学公式渲染
    html-math-method: katex
    
    # 自定义CSS
    css: assets/cv-book.css
    
  pdf:
    documentclass: scrreprt
    mainfont: "PingFang SC"
    mermaid-format: png
    geometry:
      - margin=1in
    keep-tex: true

# Mermaid配置 - 适合技术图表
mermaid:
  theme: default
  format: svg

# 执行配置 - 避免卡死
execute:
  freeze: false
  cache: false