project:
  type: book
  title: "现代计算机视觉"

book:
  title: "现代计算机视觉"
  author: "AI Assistant & You"
  date: "today"
  repo-url: "https://github.com/guxinghaoyun/quarto-web"
  repo-actions: [edit, issue]
  page-footer:
    left: "© 2025 现代计算机视觉教程"
    right: "使用 [Quarto](https://quarto.org/) 构建"
  chapters:
    # 前言（不编号）
    - index.qmd

    # 第一部分：基础理论
    - part: "第一部分：基础理论"
      chapters:
        - chapter01/chapter01.qmd
        - chapter03/chapter03.qmd

    # # 第二部分：深度学习核心
    # - part: "第二部分：深度学习核心"
    #   chapters:

    # 第三部分：前沿技术
    - part: "第三部分：前沿技术"
      chapters: 
        - chapter11/chapter11.qmd

    # 第四部分：工程实践
    - part: "第四部分：工程实践"
      chapters:
        - chapter12/chapter12.qmd

    # 参考文献（不编号）
    - references.qmd

bibliography: references.bib

format:
  html:
    # 主题和样式
    theme:
      light: cosmo
      dark: darkly
    highlight-style: arrow
    css: assets/cv-book.css

    # 字体设置（中文优化）
    mainfont: "PingFang SC, Microsoft YaHei, SimSun, serif"
    monofont: "SF Mono, Consolas, Liberation Mono, Menlo, monospace"

    # 代码设置（为Mermaid图表优化）
    code-copy: true
    code-fold: false
    code-line-numbers: false
    code-overflow: scroll
    
    # 目录和导航
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    page-navigation: true

    # 侧边栏设置 - 使用Quarto原生配置
    sidebar:
      style: "docked"
      search: false
      collapse-level: 1

    # 图片设置
    fig-cap-location: bottom
    fig-responsive: true
    fig-format: retina
    lightbox: true
    
    # 搜索和数学
    search: true
    html-math-method: katex
    
    # 布局设置
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

    # 交互体验
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    
    # 引用和脚注
    citations-hover: true
    footnotes-hover: true
    
    # 阅读体验
    reading-time: true

# 图表支持
mermaid:
  theme: default

# 执行设置
execute:
  freeze: false
  cache: false
  echo: false
  warning: false
