project:
  type: book
  title: "现代计算机视觉"

# Thesis-specific metadata
thesis-title: "现代计算机视觉"
author: 
  - name: "AI Assistant & You"
supervisor: 
  - name: "Supervisor Name"
degree: "Doctor of Philosophy"
degree-year: "2025"
declaration-text: "This is my declaration."
acknowledgements-text: "I want to thank..."

book:
  author: "AI Assistant & You"
  date: "today"
  chapters:
    - index.qmd
    - part: "第十一章：三维视觉与点云处理"
      chapters:
        - chapter11/11.0_概述.qmd
        - chapter11/11.1_相机标定与几何.qmd
        - chapter11/11.2_立体匹配与深度估计.qmd
        - chapter11/11.3_三维重建.qmd
        - chapter11/11.4_点云基础与处理.qmd
        - chapter11/11.5_PointNet系列网络.qmd
        - chapter11/11.6_3D目标检测.qmd
        - chapter11/11.7_应用案例分析.qmd
    - references.qmd

lang: zh-CN

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    highlight-style: atom-one
    mainfont: "WenQuanYi Micro Hei"
  pdf:
    documentclass: scrreprt
    mainfont: "PingFang SC"
    mermaid-format: png

mermaid:
  theme: default



