project:
  type: book
  title: "现代计算机视觉"

book:
  title: "现代计算机视觉"
  author: "AI Assistant & You"
  chapters:
    - index.qmd
    - chapter11/11.0_概述.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: false
  cache: false
