project:
  type: book
  title: "现代计算机视觉"

book:
  title: "现代计算机视觉"
  author: "AI Assistant & You"
  date: "today"
  repo-url: "https://github.com/guxinghaoyun/quarto-web"
  repo-actions: [edit, issue]
  page-footer:
    left: "© 2024 现代计算机视觉教程"
    right: "使用 [Quarto](https://quarto.org/) 构建"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "第三章：图像预处理与增强技术"
      chapters:
        - chapter03/3.0_概述.qmd
        - chapter03/3.1_图像噪声模型与评估.qmd
        - chapter03/3.2_空域平滑滤波.qmd
        - chapter03/3.3_边缘保留滤波.qmd
        - chapter03/3.4_对比度增强与直方图均衡.qmd
        - chapter03/3.5_频域增强技术.qmd
        - chapter03/3.6_Retinex与色彩校正.qmd
        - chapter03/3.7_小结与实践建议.qmd
    - part: "第十一章：三维视觉与点云处理"
      chapters:
        - chapter11/11.0_概述.qmd
        - chapter11/11.1_相机标定与几何.qmd
        - chapter11/11.2_立体匹配与深度估计.qmd
        - chapter11/11.3_三维重建.qmd
        - chapter11/11.4_点云基础与处理.qmd
        - chapter11/11.5_PointNet系列网络.qmd
        - chapter11/11.6_3D目标检测.qmd
        - chapter11/11.7_应用案例分析.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    # 主题和样式
    theme:
      light: cosmo
      dark: darkly
    highlight-style: github
    css: assets/cv-book.css
    include-after-body: assets/sidebar-accordion.html

    
    # 字体设置（中文优化）
    mainfont: "PingFang SC, Microsoft YaHei, SimSun, serif"
    monofont: "SF Mono, Consolas, Liberation Mono, Menlo, monospace"
    
    # 代码设置
    code-copy: true
    code-fold: show
    code-line-numbers: true
    code-overflow: scroll
    
    # 目录和导航
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: true
    page-navigation: true


    
    # 图片设置
    fig-cap-location: bottom
    fig-responsive: true
    fig-format: retina
    lightbox: true
    
    # 搜索和数学
    search: true
    html-math-method: katex
    
    # 交互体验
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    
    # 引用和脚注
    citations-hover: true
    footnotes-hover: true
    
    # 阅读体验
    reading-time: true

# Mermaid图表支持
mermaid:
  theme: default

# 执行设置
execute:
  freeze: false
  cache: false
  echo: true
  warning: false
